### ISSUE TITLE
Dependência inexistente

### ISSUE THREAD

**Issue by ftonato** [pythonNordeste/pyne2016#2]
Percebi que no arquivo [index.html](https://github.com/pythonNordeste/pyne2016/blob/gh-pages/index.html#L52) é chamado o arquivo/lib `owl.min.js`, mas ele não existe na pasta `js`.

``` html
<script src="js/owl.min.js"></script>
```

Na pasta `js` há um [arquivo/lib](https://github.com/pythonNordeste/pyne2016/blob/gh-pages/js/wow.min.js) chamado `wow.min.js`, pensei que esse pudesse ser o correto, mas se não for, então ele continua não sendo utilizado, logo pode ser _deletado_.

**Comment by ftonato** [comment]
E aí @gtsalles beleza?

Como a data do evento já passou então penso que _issue_ tenha se tornando irrelevante.
Se julgar necessário pode abrir a _issue_ novamente.

Abraço

**Comment by gtcarvalh0** [comment]
Opa @ftonato muito obrigado pela observação, eu infelizmente não tinha me ligado nela a tempo pro evento :(
Mas obrigado mesmo assim pela ajuda :+1:
